DROP TABLE "LOANREQUEST" IF EXISTS;

CREATE TABLE "LOANREQUEST" (
  "ID" INT NOT NULL PRIMARY KEY,
  "PROCESSID" VARCHAR(45) NULL ,
  "CUSTOMERNAME" VARCHAR(45) NULL ,
  "AMOUNT" DECIMAL(10,0) NULL
);

